baseURL = "https://www.dreamgrove.gg/"
languageCode = "en-us"
title = "Dreamgrove"
copyright = "Dreamgrove"
theme = "dg-theme"
buildDrafts = "false"
buildFuture = "false"
enableRobotsTXT = "true"

[params]
  description = "Home of all things Druid"

[taxonomies]
  series = "series"
