baseURL = "https://nervous-shockley-8d1c89.netlify.com/"
languageCode = "en-us"
title = "Dreamgrove"
copyright = "Dreamgrove"
theme = "dg-theme"
buildDrafts = "true"
buildFuture = "true"

[params]
  description = "Home of all things Druid"

[taxonomies]
  series = "series"
