[context.production.environment]
  HUGO_VERSION = "0.59.0"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.59.0"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.59.0"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo -D --config=config.toml,config.dev.toml -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -D --config=config.toml,config.dev.toml -b $DEPLOY_PRIME_URL"


