[context.production.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo -D --config=config.toml,config.dev.toml -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -D --config=config.toml,config.dev.toml -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/feral/compendium"
  to = "/feral/compendium_ko"
  force = true
  status = 200
  conditions = {Language = ["ko"]}
