name: Update JSON (Cat)

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: static/sims/cat

jobs:
  update_json:
    name: Update JSON 1T
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: one target
        run: python generate_combo.py -t 1 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Cat 1T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_2:
    needs: [ update_json ]
    name: Update JSON 2T
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: one target
        run: python generate_combo.py -t 2 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Cat 2T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_3:
    needs: [ update_json_2 ]
    name: Update JSON 3T
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: one target
        run: python generate_combo.py -t 3 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Cat 3T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_4:
    needs: [ update_json_3 ]
    name: Update JSON 4T
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: one target
        run: python generate_combo.py -t 4 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Cat 4T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_5:
    needs: [ update_json_4 ]
    name: Update JSON 5T
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: one target
        run: python generate_combo.py -t 5 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Cat 5T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_dungeon:
    name: Update JSON Dungeon
    needs: [ update_json_5 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: dungeon
        run: python generate_combo.py -d -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Cat Dungeon"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json
