name: Update JSON

on:
  workflow_dispatch:

jobs:
  update_json_heroic:
    name: Update JSON (Heroic)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: one target
        run: python generate_combo_h.py -t 1 ${{ secrets.RAIDBOTSAPI }}
      - name: two targets
        run: python generate_combo_h.py -t 2 ${{ secrets.RAIDBOTSAPI }}
      - name: three targets
        run: python generate_combo_h.py -t 3 ${{ secrets.RAIDBOTSAPI }}
      - name: four targets
        run: python generate_combo_h.py -t 4 ${{ secrets.RAIDBOTSAPI }}
      - name: five targets
        run: python generate_combo_h.py -t 5 ${{ secrets.RAIDBOTSAPI }}
      #- name: dungeon
      #  run: python generate_combo_h.py -d -m ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON heroic"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json_heroic
          path: |
            *.json

  update_json_mythic:
    name: Update JSON (Mythic)
    needs: [ update_json_heroic ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: one target
        run: python generate_combo.py -t 1 ${{ secrets.RAIDBOTSAPI }}
      - name: two targets
        run: python generate_combo.py -t 2 ${{ secrets.RAIDBOTSAPI }}
      - name: three targets
        run: python generate_combo.py -t 3 ${{ secrets.RAIDBOTSAPI }}
      - name: four targets
        run: python generate_combo.py -t 4 ${{ secrets.RAIDBOTSAPI }}
      - name: five targets
        run: python generate_combo.py -t 5 ${{ secrets.RAIDBOTSAPI }}
      #- name: dungeon
      #  run: python generate_combo.py -d -m ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name dreamgrove
          git config user.email dreamgrove@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json_mythic
          path: |
            *.json
